export const SET_MESSAGE = 'SET_MESSAGE';
export const PLAYERS_HAVE_ERROR = 'PLAYERS_HAVE_ERROR';
export const PLAYERS_ARE_LOADING = 'PLAYERS_ARE_LOADING';
export const PLAYERS_FETCH_DATA_SUCCESS = 'PLAYERS_FETCH_DATA_SUCCESS';
export const PLAYER_FETCH_DATA_SUCCESS = 'PLAYER_FETCH_DATA_SUCCESS';