export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER';
export const LOCATION_HAS_ERROR = 'LOCATION_HAS_ERROR';
export const LOCATION_IS_LOADING = 'LOCATION_IS_LOADING';
export const LOCATION_FETCH_DATA_SUCCESS = 'LOCATION_FETCH_DATA_SUCCESS';
export const SELECT_FORECAST_OPTION = 'SELECT_FORECAST_OPTION';