export const PLAYERS_HAVE_ERROR = 'PLAYERS_HAVE_ERROR';
export const PLAYERS_ARE_LOADING = 'PLAYERS_ARE_LOADING';
export const PLAYERS_FETCH_DATA_SUCCESS = 'PLAYERS_FETCH_DATA_SUCCESS';
export const PLAYER_FETCH_DATA_SUCCESS = 'PLAYER_FETCH_DATA_SUCCESS';
export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER';
export const SCHEDULE_HAS_ERROR = 'SCHEDULE_HAS_ERROR';
export const SCHEDULE_IS_LOADING = 'SCHEDULE_IS_LOADING';
export const SCHEDULE_FETCH_DATA_SUCCESS = 'SCHEDULE_FETCH_DATA_SUCCESS';